import type { SeoPublicSnapshot } from "./seo-public";

export const SEO_BUILD_FIXTURE: SeoPublicSnapshot = {
  siteUrl: "https://paladinhubv2-client.onrender.com",
  registryVersion: "fixture-client-routes-2026-09-13.1",
  snapshotVersion: "fixture-2026-09-13.2",
  generatedAtUtc: "2026-09-13T00:00:00.000Z",
  staticRoutes: [
    "/",
    "/Holy/Overview",
    "/Holy/Gear",
    "/Holy/Talents",
    "/Holy/Consumables",
    "/Holy/Rotation",
    "/Holy/Stats",
    "/Protection/Overview",
    "/Protection/Gear",
    "/Protection/Talents",
    "/Protection/Consumables",
    "/Protection/Rotation",
    "/Protection/Stats",
    "/Retribution/Overview",
    "/Retribution/Gear",
    "/Retribution/Talents",
    "/Retribution/Consumables",
    "/Retribution/Rotation",
    "/Retribution/Stats",
    "/discussions",
    "/products",
    "/privacy",
  ],
  pages: [
    {
      id: 900001,
      title: "Fixture guide",
      path: "/Guides/fixture-page",
    },
  ],
  entries: [
    {
      id: "00000000-0000-0000-0000-000000000001",
      version: 1,
      pageId: null,
      path: "*",
      title: "PaladinHub Fixture",
      description: "Deterministic SEO build fixture.",
      canonicalUrl: "",
      socialTitle: "PaladinHub Fixture",
      socialDescription: "Deterministic SEO build fixture.",
      imageUrl: "",
      index: null,
      follow: null,
    },
    {
      id: "00000000-0000-0000-0000-000000000002",
      version: 2,
      pageId: 900001,
      path: "/Guides/fixture-page",
      title: "Fixture Guide SEO",
      description: "Published Page Builder fixture metadata.",
      canonicalUrl: "",
      socialTitle: "Fixture Guide Social",
      socialDescription: "Published Page Builder fixture social metadata.",
      imageUrl: "",
      index: true,
      follow: true,
    },
    {
      id: "00000000-0000-0000-0000-000000000003",
      version: 1,
      pageId: null,
      path: "/products",
      title: "Fixture Products",
      description: "Noindex fixture route.",
      canonicalUrl: "",
      socialTitle: "Fixture Products",
      socialDescription: "Noindex fixture route.",
      imageUrl: "",
      index: false,
      follow: true,
    },
  ],
};
