import type { SeoPublicSnapshot } from "./seo-public";

export const SEO_BUILD_FIXTURE: SeoPublicSnapshot = {
  siteUrl: "https://paladinhubv2-client.onrender.com",
  registryVersion: "fixture-client-routes-2026-09-13.1",
  snapshotVersion: "fixture-2026-09-13.1",
  generatedAtUtc: "2026-09-13T00:00:00.000Z",
  staticRoutes: [
    "/",
    "/Holy/Overview",
    "/Holy/Gear",
    "/Holy/Talents",
    "/Holy/Consumables",
    "/Holy/Rotation",
    "/Holy/Stats",
    "/Protection/Overview",
    "/Protection/Gear",
    "/Protection/Talents",
    "/Protection/Consumables",
    "/Protection/Rotation",
    "/Protection/Stats",
    "/Retribution/Overview",
    "/Retribution/Gear",
    "/Retribution/Talents",
    "/Retribution/Consumables",
    "/Retribution/Rotation",
    "/Retribution/Stats",
    "/discussions",
    "/products",
    "/privacy",
  ],
  pages: [],
  entries: [],
};
