"use client";
import { useEffect,useRef,useState,type FormEvent } from "react";
import { adminRequest } from "@/lib/admin-categories";
import { fetchBackend,readApiJson } from "@/config/api";
import { spellIconSource } from "@/lib/spell-icons";

type Banner={id:string;internalName:string;title:string;text:string;imageUrl?:string|null;altText:string;buttonText?:string|null;buttonUrl?:string|null;kind:string;position:string;pages:string[];startAtUtc?:string|null;endAtUtc?:string|null;sortOrder:number;isDismissible:boolean;isActive:boolean;isArchived:boolean;isDeleted:boolean;version:number};
type Revision={id:string;version:number;action:string;actor:string;createdAtUtc:string;snapshot:Banner};
type Media={id:string;name:string;altText:string;icon:string;isArchived:boolean;isDeleted:boolean};type MediaCatalog={media:Media[]};
const blank={internalName:"",title:"",text:"",imageUrl:"",altText:"",buttonText:"",buttonUrl:"",kind:"information",position:"below-navbar",pages:"",startAtUtc:"",endAtUtc:"",sortOrder:0,isDismissible:true,isActive:true};
const local=(value?:string|null)=>value?new Date(value).toISOString().slice(0,16):"";
const utc=(value:string)=>value?new Date(value).toISOString():null;
export default function BannersAdmin(){
 const [rows,setRows]=useState<Banner[]>([]),[selected,setSelected]=useState<Banner|null>(null),[draft,setDraft]=useState(blank),[history,setHistory]=useState<Revision[]>([]),[media,setMedia]=useState<Media[]>([]);
 const [search,setSearch]=useState(""),[status,setStatus]=useState("active"),[refresh,setRefresh]=useState(0),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);const busyRef=useRef(false);
 const choose=(x:Banner|null)=>{setSelected(x);setDraft(x?{internalName:x.internalName,title:x.title,text:x.text,imageUrl:x.imageUrl??"",altText:x.altText,buttonText:x.buttonText??"",buttonUrl:x.buttonUrl??"",kind:x.kind,position:x.position,pages:x.pages.join("\n"),startAtUtc:local(x.startAtUtc),endAtUtc:local(x.endAtUtc),sortOrder:x.sortOrder,isDismissible:x.isDismissible,isActive:x.isActive}:blank);setError("");setNotice("");};
 useEffect(()=>{const c=new AbortController();void adminRequest<Banner[]>(`/Admin/api/banners?${new URLSearchParams({search,status})}`,"GET",undefined,c.signal).then(setRows).catch(e=>!c.signal.aborted&&setError(e.message));return()=>c.abort();},[search,status,refresh]);
 useEffect(()=>{const c=new AbortController();void adminRequest<MediaCatalog>("/Admin/api/media?status=active&page=1","GET",undefined,c.signal).then(x=>setMedia(x.media??[])).catch(()=>{});return()=>c.abort();},[refresh]);
 useEffect(()=>{setHistory([]);if(!selected)return;const c=new AbortController();void adminRequest<Revision[]>(`/Admin/api/banners/${selected.id}/history`,"GET",undefined,c.signal).then(setHistory).catch(e=>!c.signal.aborted&&setError(e.message));return()=>c.abort();},[selected,refresh]);
 async function mutate(path:string,method:string,body:unknown){if(busyRef.current)return;busyRef.current=true;setBusy(true);setError("");setNotice("");try{await adminRequest(path,method,body);choose(null);setRefresh(x=>x+1);setNotice("Banner saved.");}catch(e){setError(e instanceof Error?e.message:"Could not save banner.");}finally{busyRef.current=false;setBusy(false);}}
 async function upload(file:File){if(!["image/png","image/jpeg","image/gif","image/webp"].includes(file.type)||file.size<=0||file.size>5*1024*1024){setError("Choose PNG, JPEG, GIF or WebP up to 5 MB.");return;}setBusy(true);try{const csrf=await adminRequest<{token:string}>("/api/auth/csrf");const form=new FormData();form.append("file",file);const uploaded=await readApiJson<{id:string;icon?:string;url?:string;altText?:string}>(await fetchBackend("/Admin/api/spells/icons",{method:"POST",headers:{"X-CSRF-TOKEN":csrf.token},body:form}));const url=uploaded.url??(uploaded.icon?spellIconSource(uploaded.icon):`/api/spells/icons/${uploaded.id}`);setDraft(x=>({...x,imageUrl:url,altText:x.altText||uploaded.altText||file.name}));setRefresh(x=>x+1);}catch(e){setError(e instanceof Error?e.message:"Upload failed.");}finally{setBusy(false);}}
 function payload(){return{...draft,pages:draft.pages.split(/\r?\n|,/).map(x=>x.trim()).filter(Boolean),startAtUtc:utc(draft.startAtUtc),endAtUtc:utc(draft.endAtUtc),version:selected?.version??0};}
 function submit(e:FormEvent){e.preventDefault();void mutate(selected?`/Admin/api/banners/${selected.id}`:"/Admin/api/banners",selected?"PUT":"POST",payload());}
 const preview={...draft,imageUrl:draft.imageUrl.trim()};
 return <section onPaste={e=>{const f=Array.from(e.clipboardData.items).find(x=>x.type.startsWith("image/"))?.getAsFile();if(f){e.preventDefault();void upload(f);}}}>
  <h2>Banners & messages</h2><p>Schedule fields are entered in your local browser time and stored by the server as UTC.</p>
  {error?<p className="alert alert-danger" role="alert">{error}</p>:null}{notice?<p className="alert alert-success" role="status">{notice}</p>:null}
  <div className="d-flex flex-wrap gap-2 mb-3"><input className="form-control" style={{flex:"1 1 220px",minWidth:0}} type="search" value={search} placeholder="Search banners" aria-label="Search banners" onChange={e=>setSearch(e.target.value)}/><select className="form-select" style={{flex:"0 1 180px"}} value={status} aria-label="Banner status" onChange={e=>setStatus(e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option><option value="deleted">Deleted</option><option value="all">All</option></select><button type="button" className="btn btn-success" onClick={()=>choose(null)}>New banner</button></div>
  <div className="row g-3"><div className="col-12 col-xl-5"><div className="list-group">{rows.map(x=><button type="button" key={x.id} className={`list-group-item list-group-item-action${selected?.id===x.id?" active":""}`} onClick={()=>choose(x)}><strong>{x.internalName}</strong><span className="d-block">{x.position} · v{x.version} · {x.isDeleted?"deleted":x.isArchived?"archived":x.isActive?"active":"inactive"}</span></button>)}{rows.length===0?<p>No matching banners.</p>:null}</div></div>
   <div className="col-12 col-xl-7"><form onSubmit={submit}><fieldset disabled={busy||selected?.isDeleted}><label className="form-label">Internal name</label><input className="form-control mb-2" required maxLength={100} value={draft.internalName} onChange={e=>setDraft({...draft,internalName:e.target.value})}/><label className="form-label">Title</label><input className="form-control mb-2" required maxLength={200} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><label className="form-label">Text</label><textarea className="form-control mb-2" required maxLength={10000} rows={4} value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})}/>
    <label className="form-label">Image URL</label><input className="form-control mb-2" maxLength={2048} value={draft.imageUrl} onChange={e=>setDraft({...draft,imageUrl:e.target.value})}/><div className="d-flex flex-wrap gap-2 mb-2"><select className="form-select" style={{flex:"1 1 220px"}} value="" aria-label="Choose image from media library" onChange={e=>{const m=media.find(x=>x.id===e.target.value);if(m)setDraft({...draft,imageUrl:spellIconSource(m.icon),altText:draft.altText||m.altText});}}><option value="">Choose from media library…</option>{media.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><label className="btn btn-secondary mb-0">Upload<input hidden type="file" accept="image/png,image/jpeg,image/gif,image/webp" onChange={e=>{const f=e.target.files?.[0];e.target.value="";if(f)void upload(f);}}/></label></div><small className="d-block mb-2">You can also paste an image anywhere in this editor.</small><label className="form-label">Alt text</label><input className="form-control mb-2" maxLength={300} value={draft.altText} onChange={e=>setDraft({...draft,altText:e.target.value})}/>
    <div className="row"><div className="col-12 col-md-6"><label className="form-label">Button text</label><input className="form-control mb-2" maxLength={120} value={draft.buttonText} onChange={e=>setDraft({...draft,buttonText:e.target.value})}/></div><div className="col-12 col-md-6"><label className="form-label">Button URL</label><input className="form-control mb-2" maxLength={2048} value={draft.buttonUrl} onChange={e=>setDraft({...draft,buttonUrl:e.target.value})}/></div></div>
    <div className="row"><div className="col-12 col-md-6"><label className="form-label">Kind</label><select className="form-select mb-2" value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value})}><option value="information">Information</option><option value="success">Success</option><option value="warning">Warning</option></select></div><div className="col-12 col-md-6"><label className="form-label">Position</label><select className="form-select mb-2" value={draft.position} onChange={e=>setDraft({...draft,position:e.target.value})}><option value="above-navbar">Above navbar</option><option value="below-navbar">Below navbar</option><option value="above-content">Above page content</option></select></div></div>
    <label className="form-label">Page scope (one public path per line; empty = whole public site)</label><textarea className="form-control mb-2" rows={3} value={draft.pages} onChange={e=>setDraft({...draft,pages:e.target.value})}/><div className="row"><div className="col-12 col-md-6"><label className="form-label">Starts</label><input className="form-control mb-2" type="datetime-local" value={draft.startAtUtc} onChange={e=>setDraft({...draft,startAtUtc:e.target.value})}/></div><div className="col-12 col-md-6"><label className="form-label">Ends</label><input className="form-control mb-2" type="datetime-local" value={draft.endAtUtc} onChange={e=>setDraft({...draft,endAtUtc:e.target.value})}/></div></div><label className="form-label">Sort order</label><input className="form-control mb-2" type="number" value={draft.sortOrder} onChange={e=>setDraft({...draft,sortOrder:Number(e.target.value)})}/><label className="d-flex gap-2 mb-2"><input type="checkbox" checked={draft.isDismissible} onChange={e=>setDraft({...draft,isDismissible:e.target.checked})}/>Visitor can dismiss</label><label className="d-flex gap-2 mb-3"><input type="checkbox" checked={draft.isActive} onChange={e=>setDraft({...draft,isActive:e.target.checked})}/>Active</label>
    <div className={`ph-site-banner ph-site-banner--${preview.kind} mb-3`}>{preview.imageUrl?<img className="ph-site-banner-image" src={preview.imageUrl} alt={preview.altText}/>:null}<div className="ph-site-banner-body"><strong>{preview.title||"Preview title"}</strong><span>{preview.text||"Preview text"}</span></div>{preview.buttonText&&preview.buttonUrl?<span className="btn btn-sm btn-outline-light">{preview.buttonText}</span>:null}</div>
    <div className="d-flex flex-wrap gap-2"><button className="btn btn-success" type="submit">{selected?"Save changes":"Create banner"}</button>{selected&&!selected.isArchived&&!selected.isDeleted?<button className="btn btn-secondary" type="button" onClick={()=>void mutate(`/Admin/api/banners/${selected.id}/actions`,"POST",{version:selected.version,action:"archive"})}>Archive</button>:null}{selected?.isArchived&&!selected.isDeleted?<button className="btn btn-secondary" type="button" onClick={()=>void mutate(`/Admin/api/banners/${selected.id}/actions`,"POST",{version:selected.version,action:"unarchive"})}>Unarchive</button>:null}{selected&&!selected.isDeleted?<button className="btn btn-danger" type="button" onClick={()=>void mutate(`/Admin/api/banners/${selected.id}/actions`,"POST",{version:selected.version,action:"delete"})}>Delete</button>:null}</div>
   </fieldset></form>
   {selected?<><h3 className="mt-4">History</h3>{history.map(h=><details className="border rounded p-2 mb-2" key={h.id}><summary>v{h.version} · {h.action} · {new Date(h.createdAtUtc).toLocaleString()} · {h.actor}</summary><button type="button" className="btn btn-outline-primary mt-2" disabled={busy||h.version===selected.version} onClick={()=>void mutate(`/Admin/api/banners/${selected.id}/actions`,"POST",{version:selected.version,action:"restore",revisionId:h.id})}>Restore this version</button></details>)}</>:null}
  </div></div>
 </section>;
}
