"use client";
import SpellIconPicker from "@/components/admin/SpellIconPicker";
import { useEffect,useRef,useState,type FormEvent } from "react";
import { adminRequest } from "@/lib/admin-categories";
import { fetchBackend,readApiJson } from "@/config/api";
import { spellIconSource } from "@/lib/spell-icons";

type Banner={id:string;internalName:string;title:string;text:string;imageUrl?:string|null;altText:string;buttonText?:string|null;buttonUrl?:string|null;kind:string;position:string;pages:string[];startAtUtc?:string|null;endAtUtc?:string|null;sortOrder:number;isDismissible:boolean;isActive:boolean;isArchived:boolean;isDeleted:boolean;version:number};
type Revision={id:string;version:number;action:string;actor:string;createdAtUtc:string;snapshot:Banner};
type Media={id:string;name:string;altText:string;icon:string;isArchived:boolean;isDeleted:boolean};type MediaCatalog={media:Media[]};
const blank={internalName:"",title:"",text:"",imageUrl:"",altText:"",buttonText:"",buttonUrl:"",kind:"information",position:"below-navbar",pages:"",startAtUtc:"",endAtUtc:"",sortOrder:0,isDismissible:true,isActive:true};
const local=(value?:string|null)=>value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):"";
const utc=(value:string)=>value?new Date(value).toISOString():null;
export default function BannersAdmin(){
 const [rows,setRows]=useState<Banner[]>([]),[selected,setSelected]=useState<Banner|null>(null),[draft,setDraft]=useState(blank),[history,setHistory]=useState<Revision[]>([]);
 const [search,setSearch]=useState(""),[status,setStatus]=useState("active"),[refresh,setRefresh]=useState(0),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);const busyRef=useRef(false);
 const choose=(x:Banner|null)=>{setSelected(x);setDraft(x?{internalName:x.internalName,title:x.title,text:x.text,imageUrl:x.imageUrl??"",altText:x.altText,buttonText:x.buttonText??"",buttonUrl:x.buttonUrl??"",kind:x.kind,position:x.position,pages:x.pages.join("\n"),startAtUtc:local(x.startAtUtc),endAtUtc:local(x.endAtUtc),sortOrder:x.sortOrder,isDismissible:x.isDismissible,isActive:x.isActive}:blank);setError("");setNotice("");};
 useEffect(()=>{const c=new AbortController();void adminRequest<Banner[]>(`/Admin/api/banners?${new URLSearchParams({search,status})}`,"GET",undefined,c.signal).then(setRows).catch(e=>!c.signal.aborted&&setError(e.message));return()=>c.abort();},[search,status,refresh]);

 useEffect(()=>{setHistory([]);if(!selected)return;const c=new AbortController();void adminRequest<Revision[]>(`/Admin/api/banners/${selected.id}/history`,"GET",undefined,c.signal).then(setHistory).catch(e=>!c.signal.aborted&&setError(e.message));return()=>c.abort();},[selected,refresh]);
 async function mutate(path:string,method:string,body:unknown){if(busyRef.current||busy)return;busyRef.current=true;setBusy(true);setError("");setNotice("");try{await adminRequest(path,method,body);choose(null);setRefresh(x=>x+1);setNotice("Banner saved.");}catch(e){setError(e instanceof Error?e.message:"Could not save banner.");}finally{busyRef.current=false;setBusy(false);}}
 function payload(){return{...draft,pages:draft.pages.split(/\r?\n|,/).map(x=>x.trim()).filter(Boolean),startAtUtc:utc(draft.startAtUtc),endAtUtc:utc(draft.endAtUtc),version:selected?.version??0};}
 function submit(e:FormEvent){e.preventDefault();void mutate(selected?`/Admin/api/banners/${selected.id}`:"/Admin/api/banners",selected?"PUT":"POST",payload());}
 const preview={...draft,imageUrl:draft.imageUrl.trim()};
 return <section>
  <h2>Banners & messages</h2><p>Schedule fields are entered in your local browser time and stored by the server as UTC.</p>
  {error?<p className="alert alert-danger" role="alert">{error}</p>:null}{notice?<p className="alert alert-success" role="status">{notice}</p>:null}
  <div className="d-flex flex-wrap gap-2 mb-3"><input className="form-control" style={{flex:"1 1 220px",minWidth:0}} type="search" value={search} placeholder="Search banners" aria-label="Search banners" onChange={e=>setSearch(e.target.value)}/><select className="form-select" style={{flex:"0 1 180px"}} value={status} aria-label="Banner status" onChange={e=>setStatus(e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option><option value="deleted">Deleted</option><option value="all">All</option></select><button type="button" className="btn btn-success" onClick={()=>choose(null)}>New banner</button></div>
  <div className="row g-3"><div className="col-12 col-xl-5"><div className="list-group">{rows.map(x=><button type="button" key={x.id} className={`list-group-item list-group-item-action${selected?.id===x.id?" active":""}`} onClick={()=>choose(x)}><strong>{x.internalName}</strong><span className="d-block">{x.position} · v{x.version} · {x.isDeleted?"deleted":x.isArchived?"archived":x.isActive?"active":"inactive"}</span></button>)}{rows.length===0?<p>No matching banners.</p>:null}</div></div>
   <div className="col-12 col-xl-7"><form onSubmit={submit}><fieldset disabled={busy||selected?.isDeleted||selected?.isArchived}><label className="form-label" htmlFor="banner-internal-name">Internal name</label><input id="banner-internal-name" className="form-control mb-2" required maxLength={100} value={draft.internalName} onChange={e=>setDraft({...draft,internalName:e.target.value})}/><label className="form-label" htmlFor="banner-title">Title</label><input id="banner-title" className="form-control mb-2" required maxLength={200} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><label className="form-label" htmlFor="banner-text">Text</label><textarea id="banner-text" className="form-control mb-2" required maxLength={10000} rows={4} value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})}/>
    <SpellIconPicker label="Banner image" value={draft.imageUrl} disabled={busy||!!selected?.isDeleted||!!selected?.isArchived} onBusyChange={setBusy} onChange={value=>setDraft(x=>({...x,imageUrl:value?spellIconSource(value):""}))}/>
    <label className="form-label" htmlFor="banner-alt-text">Alt text</label><input id="banner-alt-text" className="form-control mb-2" maxLength={300} value={draft.altText} onChange={e=>setDraft({...draft,altText:e.target.value})}/>
    <div className="row"><div className="col-12 col-md-6"><label className="form-label" htmlFor="banner-button-text">Button text</label><input id="banner-button-text" className="form-control mb-2" maxLength={120} value={draft.buttonText} onChange={e=>setDraft({...draft,buttonText:e.target.value})}/></div><div className="col-12 col-md-6"><label className="form-label" htmlFor="banner-button-url">Button URL</label><input id="banner-button-url" className="form-control mb-2" maxLength={2048} value={draft.buttonUrl} onChange={e=>setDraft({...draft,buttonUrl:e.target.value})}/></div></div>
    <div className="row"><div className="col-12 col-md-6"><label className="form-label" htmlFor="banner-kind">Kind</label><select id="banner-kind" className="form-select mb-2" value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value})}><option value="information">Information</option><option value="success">Success</option><option value="warning">Warning</option></select></div><div className="col-12 col-md-6"><label className="form-label" htmlFor="banner-position">Position</label><select id="banner-position" className="form-select mb-2" value={draft.position} onChange={e=>setDraft({...draft,position:e.target.value})}><option value="above-navbar">Above navbar</option><option value="below-navbar">Below navbar</option><option value="above-content">Above page content</option></select></div></div>
    <label className="form-label" htmlFor="banner-page-scope-one-public-path-per-line-empty-whole-public-site">Page scope (one public path per line; empty = whole public site)</label><textarea id="banner-page-scope-one-public-path-per-line-empty-whole-public-site" className="form-control mb-2" rows={3} value={draft.pages} onChange={e=>setDraft({...draft,pages:e.target.value})}/><div className="row"><div className="col-12 col-md-6"><label className="form-label" htmlFor="banner-starts">Starts</label><input id="banner-starts" className="form-control mb-2" type="datetime-local" value={draft.startAtUtc} onChange={e=>setDraft({...draft,startAtUtc:e.target.value})}/></div><div className="col-12 col-md-6"><label className="form-label" htmlFor="banner-ends">Ends</label><input id="banner-ends" className="form-control mb-2" type="datetime-local" value={draft.endAtUtc} onChange={e=>setDraft({...draft,endAtUtc:e.target.value})}/></div></div><label className="form-label" htmlFor="banner-sort-order">Sort order</label><input id="banner-sort-order" className="form-control mb-2" type="number" value={draft.sortOrder} onChange={e=>setDraft({...draft,sortOrder:Number(e.target.value)})}/><label className="d-flex gap-2 mb-2"><input type="checkbox" checked={draft.isDismissible} onChange={e=>setDraft({...draft,isDismissible:e.target.checked})}/>Visitor can dismiss</label><label className="d-flex gap-2 mb-3"><input type="checkbox" checked={draft.isActive} onChange={e=>setDraft({...draft,isActive:e.target.checked})}/>Active</label>
    <div className={`ph-site-banner ph-site-banner--${preview.kind} mb-3`}>{preview.imageUrl?<img className="ph-site-banner-image" src={preview.imageUrl} alt={preview.altText}/>:null}<div className="ph-site-banner-body"><strong>{preview.title||"Preview title"}</strong><span>{preview.text||"Preview text"}</span></div>{preview.buttonText&&preview.buttonUrl?<span className="btn btn-sm btn-outline-light">{preview.buttonText}</span>:null}</div>
    <div className="d-flex flex-wrap gap-2"><button className="btn btn-success" type="submit">{selected?"Save changes":"Create banner"}</button>{selected&&!selected.isArchived&&!selected.isDeleted?<button className="btn btn-secondary" type="button" onClick={()=>void mutate(`/Admin/api/banners/${selected.id}/actions`,"POST",{version:selected.version,action:"archive"})}>Archive</button>:null}{selected?.isArchived&&!selected.isDeleted?<button className="btn btn-secondary" type="button" onClick={()=>void mutate(`/Admin/api/banners/${selected.id}/actions`,"POST",{version:selected.version,action:"unarchive"})}>Unarchive</button>:null}{selected&&!selected.isDeleted?<button className="btn btn-danger" type="button" onClick={()=>void mutate(`/Admin/api/banners/${selected.id}/actions`,"POST",{version:selected.version,action:"delete"})}>Delete</button>:null}</div>
   </fieldset></form>
   {selected?.isArchived&&!selected.isDeleted?<button disabled={busy} className="btn btn-secondary mt-2" type="button" onClick={()=>void mutate(`/Admin/api/banners/${selected.id}/actions`,"POST",{version:selected.version,action:"unarchive"})}>Unarchive banner</button>:null}
   {selected?<><h3 className="mt-4">History</h3>{history.map(h=><details className="border rounded p-2 mb-2" key={h.id}><summary>v{h.version} · {h.action} · {new Date(h.createdAtUtc).toLocaleString()} · {h.actor}</summary><button type="button" className="btn btn-outline-primary mt-2" disabled={busy||h.snapshot.isDeleted} onClick={()=>void mutate(`/Admin/api/banners/${selected.id}/actions`,"POST",{version:selected.version,action:"restore",revisionId:h.id})}>Restore this version</button></details>)}</>:null}
  </div></div>
 </section>;
}
