"use client";
import { useEffect, useRef, useState } from "react";
import BuilderNavigation from "@/components/admin/page-builder/BuilderNavigation";
import { adminRequest } from "@/lib/admin-categories";
import { Link } from "@/router/nextCompat";
type Page = { id:number;title:string;section:string;slug:string;isPublished:boolean;isArchived:boolean;isDeleted:boolean;version:number;updatedAt:string };
type Revision = { id:string;version:number;action:string;actor:string;createdAtUtc:string;snapshot:string };
type Snapshot = {Title:string;Section:string;Slug:string;IsPublished:boolean;IsArchived:boolean;IsDeleted:boolean;JsonLayout:string};
export default function PageHistory(){
 const [pages,setPages]=useState<Page[]>([]),[selected,setSelected]=useState<Page|null>(null),[history,setHistory]=useState<Revision[]>([]);
 const [search,setSearch]=useState(""),[status,setStatus]=useState("active"),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const lock=useRef(false);
 useEffect(()=>{const c=new AbortController();setLoading(true);void adminRequest<Page[]>("/Admin/api/page-history","GET",undefined,c.signal).then(data=>{if(!c.signal.aborted)setPages(data);}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[refresh]);
 useEffect(()=>{setHistory([]);if(!selected)return;const c=new AbortController();void adminRequest<Revision[]>(`/Admin/api/page-history/${selected.id}`,"GET",undefined,c.signal).then(data=>{if(!c.signal.aborted)setHistory(data);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[selected]);
 async function change(action:string,revisionId?:string){if(!selected||lock.current)return;if(!window.confirm(action==="restore"?"Restore this page's content, route and publication status to the selected revision?":`${action} this page?`))return;lock.current=true;setBusy(true);setError("");setNotice("");try{await adminRequest(`/Admin/api/page-history/${selected.id}`,"POST",{action,revisionId,version:selected.version});setSelected(null);setRefresh(n=>n+1);setNotice("Page saved. History is preserved.");}catch(e){setError(e instanceof Error?e.message:"Could not update page.");}finally{lock.current=false;setBusy(false);}}
 const visible=pages.filter(p=>(status==="all"||(status==="deleted"?p.isDeleted:!p.isDeleted&&(status==="archived"?p.isArchived:!p.isArchived)))&&`${p.title} ${p.section}/${p.slug}`.toLowerCase().includes(search.toLowerCase()));
 return <section><BuilderNavigation/><h2>Page history and recovery</h2>{error?<p role="alert" className="alert alert-danger">{error}</p>:null}{notice?<p role="status" className="alert alert-success">{notice}</p>:null}
 <div className="d-flex flex-wrap gap-2 mb-3"><input aria-label="Search pages" className="form-control" style={{flex:"1 1 180px",minWidth:0}} value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Page status" className="form-select" style={{flex:"1 1 130px",minWidth:0}} value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Active</option><option value="archived">Archived</option><option value="deleted">Deleted</option><option value="all">All</option></select><button className="btn btn-secondary" disabled={busy||loading} onClick={()=>{setSelected(null);setRefresh(n=>n+1);}}>Refresh</button></div>
 <div className="row g-3"><div className="col-12 col-xl-7">{loading?<p>Loading pages…</p>:<table className="table table-dark table-striped admin-record-table"><thead><tr><th>Page</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><td data-label="Page" style={{overflowWrap:"anywhere"}}>{p.title}<small className="d-block">/{p.section}/{p.slug}</small></td><td data-label="Status">{p.isDeleted?"Deleted":p.isArchived?"Archived":p.isPublished?"Published":"Draft"}</td><td data-label="Actions"><button className="btn btn-primary" disabled={busy} onClick={()=>{setSelected(p);setError("");setNotice("");}}>History / actions</button></td></tr>)}</tbody></table>}</div>
 <div className="col-12 col-xl-5" style={{minWidth:0}}>{selected?<><h3 style={{overflowWrap:"anywhere"}}>{selected.title}</h3><div className="d-flex flex-wrap gap-2 mb-3">{!selected.isDeleted?<><button className="btn btn-secondary" disabled={busy} onClick={()=>void change(selected.isArchived?"unarchive":"archive")}>{selected.isArchived?"Unarchive as draft":"Archive"}</button><button className="btn btn-danger" disabled={busy} onClick={()=>void change("delete")}>Delete page</button>{!selected.isArchived?<Link className="btn btn-primary" to={`/Admin/PageBuilder/Edit?id=${selected.id}`}>Edit page</Link>:null}</>:null}</div>
 {history.map(r=>{const snapshot=JSON.parse(r.snapshot) as Snapshot;return <details key={r.id} className="border rounded p-2 mb-2"><summary>v{r.version} · {r.action} · {new Date(r.createdAtUtc).toLocaleString()}</summary><p style={{overflowWrap:"anywhere"}}>{r.actor} · {snapshot.Title}</p><p style={{overflowWrap:"anywhere"}}>/{snapshot.Section}/{snapshot.Slug}</p><p>{snapshot.IsDeleted?"Deleted":snapshot.IsArchived?"Archived":snapshot.IsPublished?"Published":"Draft"}</p>{!snapshot.IsDeleted?<button className="btn btn-outline-primary" disabled={busy||r.version===selected.version} onClick={()=>void change("restore",r.id)}>Restore revision</button>:null}</details>;})}</>:<p>Select a page to manage its archive and revisions.</p>}</div></div></section>;
}
