import AppEntry from "@/app/AppEntry";

export function generateStaticParams() {
  return [
  { slug: ["Home", "Home"] },
  { slug: ["Holy", "Overview"] },
  { slug: ["Holy", "Gear"] },
  { slug: ["Holy", "Talents"] },
  { slug: ["Holy", "Consumables"] },
  { slug: ["Holy", "Rotation"] },
  { slug: ["Holy", "Stats"] },
  { slug: ["Protection", "Overview"] },
  { slug: ["Protection", "Gear"] },
  { slug: ["Protection", "Talents"] },
  { slug: ["Protection", "Consumables"] },
  { slug: ["Protection", "Rotation"] },
  { slug: ["Protection", "Stats"] },
  { slug: ["Retribution", "Overview"] },
  { slug: ["Retribution", "Gear"] },
  { slug: ["Retribution", "Talents"] },
  { slug: ["Retribution", "Consumables"] },
  { slug: ["Retribution", "Rotation"] },
  { slug: ["Retribution", "Stats"] },
  { slug: ["Discussions", "Index"] },
  { slug: ["Discussions", "Create"] },
  { slug: ["Merchandise", "Merchandise"] },
  { slug: ["Merchandise", "List"] },
  { slug: ["Products"] },
  { slug: ["Cart", "MyCart"] },
  { slug: ["Cart", "Archive"] },
  { slug: ["Checkout", "Start"] },
  { slug: ["Checkout", "Shipping"] },
  { slug: ["Checkout", "Payment"] },
  { slug: ["Checkout", "Card"] },
  { slug: ["Checkout", "Review"] },
  { slug: ["Checkout", "Registered"] },
  { slug: ["Checkout", "Success"] },
  { slug: ["Checkout", "Failure"] },
  { slug: ["Account", "Login"] },
  { slug: ["Account", "Register"] },
  { slug: ["Account", "MyAccount"] },
  { slug: ["Account", "AccountDetails"] },
  { slug: ["Account", "ChangePassword"] },
  { slug: ["Account", "Connections"] },
  { slug: ["Account", "Enable2FA"] },
  { slug: ["Account", "PaymentMethods"] },
  { slug: ["Account", "AddPaymentMethod"] },
  { slug: ["Account", "Privacy"] },
  { slug: ["Account", "Security"] },
  { slug: ["Account", "Settings"] },
  { slug: ["Account", "TransactionHistory"] },
  { slug: ["Account", "LoginWith2fa"] },
  { slug: ["Account", "RecoveryCodeLogin"] },
  { slug: ["Account", "VerifyEmail"] },
  { slug: ["Account", "ShowRecoveryCodes"] },
  { slug: ["Home", "Privacy"] },
  { slug: ["Home", "ThanksForPurchasing"] },
  { slug: ["Admin", "Database"] },
  { slug: ["Admin", "Items", "Create"] },
  { slug: ["Admin", "Spells", "Create"] },
  { slug: ["Admin", "PageBuilder", "Create"] },
  { slug: ["Admin", "PromoCodes"] },
  { slug: ["Error", "404"] },
  { slug: ["Error", "500"] },
  { slug: ["login"] },
  { slug: ["register"] },
  { slug: ["account"] },
  { slug: ["cart"] },
  { slug: ["checkout"] },
  { slug: ["products"] },
  { slug: ["discussions"] },
  { slug: ["privacy"] },
  { slug: ["admin"] }
  ];
}

export default function Page() { return <AppEntry />; }
